engines:
  brakeman:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
exclude_paths:
  - coverage/**/*
ratings:
  paths:
  - app/**/*.rb
  - spec/**/*.rb
