language: ruby
rvm: 2.3.0
before_script:
  - mysql -e 'create database aggressive_epsilon_test'
  - cp config/database.yml.example config/database.yml
script:
  - bundle exec rake db:reset
  - bundle exec rake travis
notifications:
  email:
    on_success: never
    on_failure: change
    recipients: programmers@admin.umass.edu
